config/routes.rb
Fashionhub::Application.routes.draw do
  mount RailsAdmin::Engine => '/fh-admin', as: 'rails_admin'

  devise_for :users
  resources :carts do
    resources :products do
      member do
        delete :remove
      end
    end
    resources :brands do
      member do
        post :order
      end
    end
  end
  resources :stores
  resources :brands do
    resources :brand_files
    resources :collections do
      resources :products
    end
    resources :orders
  end
  resources :favorites do
    member do
      post :product
      post :collection
      post :favorite
    end
  end
  resources :connections, only: [] do
    member do
      post :request_brand
      put :accept_store
      delete :refuse_store
      post :request_store
      put :accept_brand
      delete :refuse_brand
    end
  end
  resources :messages
  resources :search

  root to: 'home#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :dashboard do
      member do
        post 'user_approval'
      end
      collection do
        get 'orders'
        get 'transactions'
      end
    end
  end

  match "painel", to: "home#dashboard", via: 'get', as: 'dashboard_detail'
  match "loja", to: "home#store", via: 'get', as: 'store_detail'
  match "marca", to: "home#brand", via: 'get', as: 'brand_detail'
  match "favorito", to: "home#favorite", via: 'get', as: 'favorite_detail'
  match "activities", to: "home#activities", via: 'get', as: 'activities_detail'
  match "registro", to: "home#register", via: 'get', as: 'register_detail'
  match "conexao", to: "home#connection", via: 'get', as: 'connection_detail'

  match "empresa", to: "home#about", via: 'get', as: 'about'
  match "termos", to: "home#terms_use", via: 'get', as: 'terms'
  match "privacidade", to: "home#privacy", via: 'get', as: 'privacy'
  match "contato", to: "home#contact", via: 'get', as: 'contact'
  post 'contact', to: 'home#send_contact', as: 'send_contact'
  get 'historico-compras', to: 'home#orders', as: 'history_orders'


  # Tirar quando for implementar a página da Marca
  if Rails.env.development?
    match "email", to: "home#layout_email", via: 'get', as: 'email_detail'
  end
  #match "marca_fechada", :to => "home#brand_closed", :via => 'get', :as => 'brand_closed_detail'
  #match "produto", :to => "home#product", :via => 'get', :as => 'product_detail'
  #match "carrinho", :to => "home#cart", :via => 'get', :as => 'cart_detail'
  #match "colecao", :to => "home#collection", :via => 'get', :as => 'collection_detail'
  #match "upload_arquivo", :to => "home#upload_file", :via => 'get', :as => 'upload_file_detail'
  #match "nova_colecao", :to => "home#create_collection", :via => 'get', :as => 'create_collection_detail'
  #match "editar_colecao", :to => "home#edit_collection", :via => 'get', :as => 'edit_collection_detail'
  #match "novo_produto", :to => "home#create_product", :via => 'get', :as => 'create_product_detail'
  #match "editar_produto", :to => "home#edit_product", :via => 'get', :as => 'edit_product_detail'
  #match "editar", :to => "home#edit_profile", :via => 'get', :as => 'edit_detail'
  #match "editar_loja", :to => "home#edit_profile_store", :via => 'get', :as => 'edit_store_detail'
  #match "buscar", :to => "home#search", :via => 'get', :as => 'search'

  namespace :dev do
    resources :mailing do
      collection do
        get 'confirmation'
        get 'password'
        get 'user_approved'
        get 'user_refused'
        get 'contact'
      end
    end
  end
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :brand
  has_many :products, dependent: :destroy

  def representative_sample
    products.first.representative_sample unless products.empty?
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  respond_to :html
  before_action :set_collection

  before_filter :check_current_user_authorization, only: [:edit, :update, :destroy, :new, :create]
  before_filter :check_current_user_store_connected_to_brand, only: [:index, :show]

  def index
    @collection = @brand.collections.joins(:products).where(release: true).last
  end

  def show
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
  	@collection = Collection.new(collection_params)
    @collection.brand = @brand
    flash[:notice] = "Coleção criada com sucesso!" if @collection.save
    respond_with(@brand, @collection, location: new_brand_collection_path(@brand))
  end

  def update
  	flash[:notice] = "Coleção atualizado com sucesso!" if @collection.update(collection_params)
  	respond_with(@brand, @collection, location: edit_brand_collection_path(@brand, @collection))
  end

  def destroy
    @collection.destroy
    respond_with(@brand, @collection, location: new_brand_collection_path(@brand))
  end

  private
    def set_collection
      @collection = Collection.find(params[:id]) if params[:id]
      @brand = Brand.find(params[:brand_id]) if params[:brand_id]
    end

    def collection_params
      params.require(:collection).permit(:name, :delivery_date, :release)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper

  def collection_image collection
  	(collection.representative_sample ? collection.representative_sample : 'no-product.jpg')
  end

end

app/views/collections/edit.html.haml
.banner
  .container
    =render "layouts/actionbar", user: current_user

.container
  .row
    .span12
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
          = link_to "Gerenciamendo de Coleções", new_brand_collection_path(current_user)
          &#187;
        %h1
          %a.ellipsis= @collection.name

      %hr

      = link_to "Novo Produto", new_brand_collection_product_path(@brand, @collection), :class => "btn btn-primary pull-right"
      %a.btn.btn-disabled.pull-right.margin-right{data: {toggle: "modal"}, :href => "#modaleditcollection"}
        Editar Coleção
      = link_to "Excluir Coleção", brand_collection_path(@brand.id, @collection.id), {data: {toggle: "modal", method: "delete"}, class: "btn btn-disabled pull-right margin-right"}


      .clearfix
      %br

      .row
        - @collection.products.each do |product|
          .span140.span220
            = link_to edit_brand_collection_product_path(@brand, @collection, product) do
              = image_tag product_image(product), :class => "size-medium"
              .connection-name.ellipsis
                = product.name

#modaleditcollection.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel EDITAR COLEÇÃO
  .modal-body
    .container.container-modal
      = simple_form_for [@brand, @collection] do |f|
        .form-inputs
          = f.input :name, autofocus: true
          = f.input :delivery_date
          %label.checkbox
            = f.input :release

          .clearfix
          %button.btn.btn-primary.pull-right Editar

  .hr-arabesc
  .modal-footer

app/views/collections/index.html.haml
.banner
  .container
    = render 'layouts/actionbar_brand'

.container
  .row
    .span3
      = render 'layouts/collectionbar', user: @brand, single_element: true

    .span9
      .collection-title
        %h2
          = link_to @brand.name, brand_path(@brand)
          &#187;
        %h1
          %a Coleções

      %hr

      - if user_signed_in? && current_user.id == @brand.id || current_user.has_connection_with(@brand)
        - if @collection
          %h4.title
            .pull-left
              %a.text= @collection.name

          .myCarousel
            .carousel-inner
              .active.item
                %ul.thumbnails
                  - @collection.products.each do |prod|
                    = render 'product_avatar', product: prod, user: current_user
        - elsif current_user.id == @brand.id
          - # ajeitar isso Renata
          %p
            Você ainda não possui nenhuma coleção.

          = link_to new_brand_collection_path(@brand), class: 'btn btn-primary pull-right margin-right' do
            Criar Nova Coleção
        - else
          %p
            %i= "#{@brand.name} ainda não criou nenhuma coleção no FashionHub."
          %br
          .hr-arabesc
      - else
        - # ajeitar isso Renata
        %p
          Você precisa se conectar a esta marca para poder visualizar suas coleções.

= render 'brands/payment_conditions'

app/views/collections/new.html.haml
.banner
  .container
    = render "layouts/actionbar", user: @brand

.container.background-column.gold
  .row
    .span3
      = render "layouts/sidebar", user: @brand

    .span9
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Gerenciamento de Coleções

      %hr

      %a.btn.btn-primary.pull-right.margin-right{data:{toggle: "modal"}, href: "#modalcollection"}
        Nova Coleção
      .clearfix
      %br

      .row
        - unless @brand.collections.empty?
          - @brand.collections.order(:id).each do |col|
            .span140.span175
              = link_to edit_brand_collection_path(@brand.id, col.id) do
                = image_tag collection_image(col), class: "size-small"
                .connection-name.ellipsis
                  = col.name
        - else
          .span9
            %span
              %i Nenhuma coleção cadastrada.
            %br
            %br
            .hr-arabesc

#modalcollection.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel NOVA COLEÇÃO
  .modal-body
    .container.container-modal
      = simple_form_for [@brand, @collection] do |f|
        .form-inputs
          = f.input :name, autofocus: true
          = f.input :delivery_date
          %label.checkbox
            = f.input :release

          .clearfix
          %button.btn.btn-primary.pull-right Adicionar

  .hr-arabesc
  .modal-footer

app/views/collections/show.html.haml
.banner
  .container
    = render 'layouts/actionbar_brand'

.container.background-column.gold
  .row
    .span3
      = render 'layouts/collectionbar', user: @brand, single_element: false

    .span9
      .collection-title
        %h2
          = link_to @brand.name, brand_path(@brand)
          &#187;
        %h1
          %a Coleções

      %hr

      %h4.title
        .pull-left
          %a.text= @collection.name

      .myCarousel
        .carousel-inner
          .active.item
            %ul.thumbnails
              - @collection.products.each do |prod|
                = render 'product_avatar', product: prod, user: current_user

= render 'brands/payment_conditions'