config/routes.rb
Fashionhub::Application.routes.draw do
  mount RailsAdmin::Engine => '/fh-admin', as: 'rails_admin'

  devise_for :users
  resources :carts do
    resources :products do
      member do
        delete :remove
      end
    end
    resources :brands do
      member do
        post :order
      end
    end
  end
  resources :stores
  resources :brands do
    resources :brand_files
    resources :collections do
      resources :products
    end
    resources :orders
  end
  resources :favorites do
    member do
      post :product
      post :collection
      post :favorite
    end
  end
  resources :connections, only: [] do
    member do
      post :request_brand
      put :accept_store
      delete :refuse_store
      post :request_store
      put :accept_brand
      delete :refuse_brand
    end
  end
  resources :messages
  resources :search

  root to: 'home#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :dashboard do
      member do
        post 'user_approval'
      end
      collection do
        get 'orders'
        get 'transactions'
      end
    end
  end

  match "painel", to: "home#dashboard", via: 'get', as: 'dashboard_detail'
  match "loja", to: "home#store", via: 'get', as: 'store_detail'
  match "marca", to: "home#brand", via: 'get', as: 'brand_detail'
  match "favorito", to: "home#favorite", via: 'get', as: 'favorite_detail'
  match "activities", to: "home#activities", via: 'get', as: 'activities_detail'
  match "registro", to: "home#register", via: 'get', as: 'register_detail'
  match "conexao", to: "home#connection", via: 'get', as: 'connection_detail'

  match "empresa", to: "home#about", via: 'get', as: 'about'
  match "termos", to: "home#terms_use", via: 'get', as: 'terms'
  match "privacidade", to: "home#privacy", via: 'get', as: 'privacy'
  match "contato", to: "home#contact", via: 'get', as: 'contact'
  post 'contact', to: 'home#send_contact', as: 'send_contact'
  get 'historico-compras', to: 'home#orders', as: 'history_orders'


  # Tirar quando for implementar a página da Marca
  if Rails.env.development?
    match "email", to: "home#layout_email", via: 'get', as: 'email_detail'
  end
  #match "marca_fechada", :to => "home#brand_closed", :via => 'get', :as => 'brand_closed_detail'
  #match "produto", :to => "home#product", :via => 'get', :as => 'product_detail'
  #match "carrinho", :to => "home#cart", :via => 'get', :as => 'cart_detail'
  #match "colecao", :to => "home#collection", :via => 'get', :as => 'collection_detail'
  #match "upload_arquivo", :to => "home#upload_file", :via => 'get', :as => 'upload_file_detail'
  #match "nova_colecao", :to => "home#create_collection", :via => 'get', :as => 'create_collection_detail'
  #match "editar_colecao", :to => "home#edit_collection", :via => 'get', :as => 'edit_collection_detail'
  #match "novo_produto", :to => "home#create_product", :via => 'get', :as => 'create_product_detail'
  #match "editar_produto", :to => "home#edit_product", :via => 'get', :as => 'edit_product_detail'
  #match "editar", :to => "home#edit_profile", :via => 'get', :as => 'edit_detail'
  #match "editar_loja", :to => "home#edit_profile_store", :via => 'get', :as => 'edit_store_detail'
  #match "buscar", :to => "home#search", :via => 'get', :as => 'search'

  namespace :dev do
    resources :mailing do
      collection do
        get 'confirmation'
        get 'password'
        get 'user_approved'
        get 'user_refused'
        get 'contact'
      end
    end
  end
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.admin?
        render 'admin/dashboard/index'
      else
        render 'dashboard'
      end
    end
  end

  def favorite
    @favorites = current_user.favorites
  end

  def activities
    not_found if !current_user.store?

    brands = current_user.brands.where(connections: {accepted: true}).pluck(:id)
    collections = Collection.joins(:products).where(brand_id: brands)
    files = BrandFile.where(brand_id: brands)
    @activities = [collections, files].flatten.sort_by(&:created_at).reverse
    @activities = Kaminari.paginate_array(@activities).page(params[:page]).per(50)
  end

  def send_contact
    ContactMailer.user_contact(params[:name], params[:email], params[:subject], params[:message]).deliver
    flash[:notice] = "Mensagem enviada. Obrigado pelo seu contato."
    redirect_to contact_path
  end

  def orders
    @orders = (current_user.store? ? Order.where(store: current_user) : Order.where(brand: current_user)).page(params[:page] || 1)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar.about
      %ul.nav.nav-list.bs-docs-sidenav
        %li.active
          %a{:href => about_path}
            Empresa
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li
          %a{:href => privacy_path}
            Privacidade
            %i.icon-chevron-right
        %li
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify

      %h2.margin-bottom2 O que é o FashionHub?

      %p FashionHub é uma plataforma online de atacado de moda, que conecta marcas e lojistas com o objetivo de realizar negócios e networking.
      %p Nossa plataforma é desenvolvida por quem conhece de perto as rotinas do dia-a-dia, tanto dos gestores das marcas, quanto dos lojistas.
      %p Hoje em dia, muito tempo é mal empregado, com atividades manuais e não escaláveis, onerosas e passíveis de erros, e que pesam a carga de trabalho das empresas.
      %p Somos apaixonados por novas tecnologias e entusiastas no desenvolvimento de soluções, que resolvem problemas reais das empresas.
      %p Desenvolvemos soluções para empresas que buscam posicionamento diferenciado em um mercado competitivo e dinâmico, explorando ao máximo, o potencial que a tecnologia disponibiliza para otimizar seus processos e resultados.
      
      .hr-arabesc.margin-top2 

app/views/home/activities.html.haml
.banner
  .container
    = render "layouts/actionbar", user: current_user

.container
  .row          
    .span12
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Atividade dos Contatos
          
      %hr
              
      .row
        - unless @activities.count > 0
          .span12
            %p
              %i Seus contatos não realizaram nenhuma atividade recentemente.
        - else
          .span12
            %ul.unstyled.notification
              - @activities.each do |atv|
                %li
                  %i.icon-plus
                  = user_link_to atv.brand, {class: ''} do
                    = atv.brand.name 
                  adicionou 
                  - if atv.class.name == 'Collection'
                    coleção
                    = link_to(atv.name, brand_collection_path(atv.brand, atv))
                  - elsif atv.class.name == 'BrandFile'
                    material
                    = link_to(atv.title, brand_brand_file_path(atv.brand, atv))

app/views/home/brand.html.haml
.container 
  .main-content.content-image-description
  
    .row
      .span12.title
        %h1.small-font-weight.text-center Leve sua Marca
        %h3.small-font-weight.text-center para todos os lugares
        %br
        .hr-arabesc.margin-bottom2
    
      .row
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexbrand01.png' 
            .span5
              %h3 Facilidade
              %p Crie facilmente suas coleções e conecte-se com compradores.
        
        .span12.images-description
          .row
            .span5
              %h3 Volume de Vendas
              %p Aumente o volume de vendas da sua marca.
              %p Maior alcance estratégico. Prospecção de novos clientes e novos mercados.
            .span4.pull-right
              = link_to register_detail_path do
                = image_tag 'indexbrand02.png'
  
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexbrand03.png' 
            .span5
              %h3 Acompanhe em Tempo Real
              %p Acompanhe em tempo real a performance de vendas de suas coleções.
              %p Receba notificações de novos pedidos, mensagens e solicitações de conexão.
              
        .span12.images-description
          .row
            .span5
              %h3 Relatórios
              %p Relatórios com dados extremamente úteis para tomada de decisões estratégicas e mais inteligentes em seu negócio.
            .span4.pull-right
              = link_to register_detail_path do
                = image_tag 'indexbrand04.png'
          
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexstore01.png' 
            .span5
              %h3 Showroom 24H
              %p Seu showroom disponível 24 horas por dia, todos os dias do ano.
        
        .span12.hr-arabesc.margin
        
        .row
          .span12.text-center
            = link_to new_brand_path, :class => "btn btn-primary" do
              Fazer meu Cadastro como marca
              %i.icon-chevron-right

app/views/home/connection.html.haml
.banner
  .container
    =render "layouts/actionbar", user: current_user

.container.background-column.gold
  .row
    .span3 
      =render "layouts/sidebar", user: current_user
      
    .span9
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Conexões
          
      %hr
      
      .row
        - unless current_user.firmed_connections.empty?
          - current_user.firmed_connections.each do |conn|
            .span140
              - if current_user.store?
                = link_to brand_path(conn.brand) do
                  .thumbnail
                    = image_tag conn.brand.logo
                  .connection-name.ellipsis
                    = conn.brand.name
                -#%a.btn.btn-disabled.btn-block
                  Desconectar
              - elsif current_user.brand?
                = link_to store_path(conn.store) do
                  .thumbnail
                    = image_tag conn.store.logo
                  .connection-name
                    = conn.store.name
                -#%a.btn.btn-disabled.btn-block
                  Desconectar
        - else
          .span9
            %p.margin-left
              %i Nenhuma conexão estabelecida até o momento. Utilize a busca para encontrar novas conexões do seu interesse.
            %br
            .hr-arabesc

app/views/home/contact.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar.about
      %ul.nav.nav-list.bs-docs-sidenav
        %li
          %a{:href => about_path}
            Empresa
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li
          %a{:href => privacy_path}
            Privacidade
            %i.icon-chevron-right
        %li.active
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify

      %h2 Contato

      = form_tag(send_contact_path, method: :post) do |f|
        .control-group
          = label_tag :name, "Nome"
          = text_field_tag :name, nil, class: 'span8', required: true
        .control-group
          = label_tag :email, "E-mail"
          = email_field_tag :email, nil, class: 'span8', required: true
        .control-group
          = label_tag :subject, "Assunto"
          = text_field_tag :subject, nil, class: 'span8'
        .control-group
          = label_tag :message, "Mensagem"
          = text_area_tag :message, nil, :rows => 15, class: 'span8', required: true
      

        = submit_tag "Enviar", class: 'btn btn-primary pull-right'
        .clearfix

app/views/home/dashboard.html.haml
.banner
  .container
    = render "layouts/actionbar", user: current_user

.container.background-column.gold
  .row
    .span3
      = render "layouts/sidebar", user: current_user

    .span9
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
        %h1
          %a Painel

      %hr

      %ul.inline.stats
        %li
          = link_to connection_detail_path do
            - connections = current_user.connections.where(accepted: true).count
            %strong= connections
            .div= connections == 1 ? 'Conexão' : 'Conexões'

        - if current_user.brand?
          %li
            = link_to history_orders_path do
              - orders = current_user.total_orders
              %strong= orders
              .div= orders == 1 ? 'Venda' : 'Vendas'
        - elsif current_user.store?
          %li
            = link_to history_orders_path do
              - orders = current_user.total_orders
              %strong= orders
              .div= orders == 1 ? 'Compra' : 'Compras'

        - if current_user.brand?
          %li
            = link_to new_brand_collection_path(current_user) do
              - collections = current_user.collections.count
              %strong= collections
              .div= collections == 1 ? 'Coleção' : 'Coleções'

        - if current_user.brand?
          %li
            = link_to new_brand_collection_path(current_user) do
              - products = current_user.total_products
              %strong= products
              .div= products == 1 ? 'Produto' : 'Produtos'
        - elsif current_user.store?
          %li
            = link_to favorite_detail_path do
              - favorites = current_user.total_favorites
              %strong= favorites
              .div= favorites == 1 ? 'Favorito' : 'Favoritos'

        - if current_user.brand?
          %li
            = link_to new_brand_brand_file_path(current_user) do
              - files = current_user.brand_files.count
              %strong= files
              .div= files == 1 ? 'Arquivo' : 'Arquivos'

      - unless current_user.pending_connections.empty?
        %h4.title
          .pull-left
            %a.text
              Contatos Pendentes

        %ul.accept-contact.unstyled
          - current_user.pending_connections.each do |conn|
            %li
              - if current_user.brand?
                = link_to store_path(conn.store) do
                  =image_tag (conn.store.logo), class: "pull-left"
                .text.pull-left
                  = link_to conn.store.name, store_path(conn.store)
                  solicitou uma conexão com sua marca
                =link_to "Aceitar", accept_store_connection_path(conn.store), class: "btn btn-disabled", data: {method: :put}
                =link_to "Recusar", refuse_store_connection_path(conn.store), class: "btn btn-disabled", data: {method: :delete}
              - elsif current_user.store?
                = link_to brand_path(conn.brand) do
                  = image_tag (conn.brand.logo), class: "pull-left"
                .text.pull-left
                  = link_to conn.brand.name, brand_path(conn.brand)
                  solicitou uma conexão com sua loja
                =link_to "Aceitar", accept_brand_connection_path(conn.brand), class: "btn btn-disabled", data: {method: :put}
                =link_to "Recusar", refuse_brand_connection_path(conn.brand), class: "btn btn-disabled", data: {method: :delete}


      -# Mensagens
      %h4.title
        .pull-left
          %a.text
            Mensagens
        .pull-right
          = link_to messages_path, class: 'more button' do
            Ver Mais
            = image_tag 'ico-arrow-right.png'

      %ul.unstyled.notification
        - if Message.unread_messages(current_user.id).empty?
          %p.margin-left
            %i Você não possui nenhuma mensagem nova.
        - else
          - Message.unread_messages(current_user.id).where(last_message: true).each do |msg|
            - sender = User.find msg.sender_id
            %li
              %i.icon-envelope
              = user_link_to sender, class: '' do
                = sender.name
              lhe enviou uma
              = link_to "nova mensagem", message_path(msg.sender_id)
              = "em #{l msg.created_at, format: :short}"

      -# Compras
      - if current_user.brand? && !current_user.orders.where(pending: true).empty?
        %h4.title
          .pull-left
            %a.text
              Compras Pendentes

          .pull-right
            = link_to brand_orders_path(current_user), class: 'more button' do
              Ver Mais
              = image_tag 'ico-arrow-right.png'

        %ul.accept-contact.unstyled
          - current_user.orders.where(pending: true).each do |order|
            %li
              = image_tag order.store.logo, :class => "pull-left"

              .text.pull-left
                = link_to order.store.name, store_path(order.store)
                = "enviou um pedido de compra às #{order.created_at.strftime('%H:%M do dia %d/%m/%Y')}"

              = link_to 'Ver Detalhes', brand_order_path(current_user, order), class: 'btn btn-disabled'

      - if current_user.store?
        %h4.title
          .pull-left
            %a.text
              Atividade dos Contatos

          .pull-right
            = link_to activities_detail_path, class: 'more button' do
              Ver Mais
              = image_tag 'ico-arrow-right.png'

        %ul.unstyled.notification
          - brands = current_user.brands.where(connections: {accepted: true}).pluck(:id)
          - collections = Collection.joins(:products).where(brand_id: brands).limit(5)
          - files = BrandFile.where(brand_id: brands).limit(5)
          - activities = [collections, files].flatten.sort_by(&:created_at).reverse
          - unless activities.count > 0
            %p.margin-left
              %i Seus contatos não realizaram nenhuma atividade recentemente.
          - else
            - activities.each do |atv|
              %li
                %i.icon-plus
                = user_link_to atv.brand, {class: ''} do
                  = atv.brand.name
                adicionou
                - if atv.class.name == 'Collection'
                  coleção
                  = link_to(atv.name, brand_collection_path(atv.brand, atv))
                - elsif atv.class.name == 'BrandFile'
                  material
                  = link_to(atv.title, atv.file.url, target: '_blank')

app/views/home/favorite.html.haml
.banner
  .container
    = render "layouts/actionbar", user: current_user

.container
  .row
    .span12
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Favoritos

      %hr

      .row
        - unless @favorites.count > 0
          .span12
            %p
              %i Você ainda não possui produtos favoritados.
            %br
            .hr-arabesc
        - else
          - @favorites.each do |favorite|
            .span12
              .row
                .span2
                  = link_to brand_collection_product_path(favorite.product.collection.brand, favorite.product.collection, favorite.product) do
                    = image_tag favorite.product.representative_sample, class: 'margin-bottom'
                  = link_to favorite_favorite_path(favorite.product), class: "btn btn-primary btn-icon btn-block", data: {method: :post} do
                    Favorito
                    %i.icon-ok

                .span10
                  .details.favorite-details
                    .product-title
                      %p
                        %span
                          = link_to favorite.product.collection.brand.name, brand_path(favorite.product.collection.brand)
                          |
                          = link_to favorite.product.name, brand_collection_product_path(favorite.product.collection.brand, favorite.product.collection, favorite.product)
                          = "(#{favorite.product.code})"
                        = number_to_currency(favorite.product.price)

                    .clearfix


                  = render "table_buy", cart: current_user.shopping_cart, product: favorite.product, favorite: true
              %hr

app/views/home/index.html.haml
.banner
  .banner-image
    .container
      .banner-message
        %span Showroom Online
        %br
        Modernizamos o processo de compras de atacado, conectando marcas e lojistas 
        para realizarem negócios escaláveis e mais inteligentes em nossa plataforma.
        = link_to register_detail_path, :class => "btn btn-primary pull-right" do
          Fazer meu Cadastro
          %i.icon-chevron-right
        .clearfix
        
      .row.arrow-down
        .span12.text-center
          %a{:href => "#index"}= image_tag 'arrow-down.png' 
    
#index.container
 
  .main-content
    .row
      .span12.text-center.title
        %h3 
          %span Crie suas Coleções e Faça Pedidos, 
          %br
          a qualquer hora e em qualquer lugar.
        .hr-arabesc
    .row
      .span12.images-description
        .row
          .span7
            = image_tag 'index03.jpg' 
          .span5
            %h3 Produtividade
            %p 
              Uso da 
              %strong tecnologia 
              para 
              %strong promover a 
              %strong redução de custos
              , e 
              %strong aumentar 
              o fluxo de 
              %strong produtividade 
              de sua equipe.
            %p 
              %stronge Libere mais tempo 
              para focar nas atividades 
              %strong estratégicas
              , que 
              %strong potencializam
              a 
              %strong rentabilidade 
              e a 
              %strong eficiência 
              do seu negócio. 
      
.background-color
  .container
    .span12.images-description
      .row
        .span5
          %h3 Simplicidade
          %p 
            Interface 
            %strong intuitiva 
            e 
            %strong fácil 
            de usar. 
          %p 
            Plataforma 100% 
            %strong online/nuvem.
          %p 
            Gerencie todos os seus pedidos de maneira mais 
            %strong simples 
            e 
            %strong ágil, centralizados 
            em um só lugar. 
          %p Elimine os processos manuais de preenchimento de planilhas e envio de inúmeros e-mails. 
        .span7.pull-right
          = image_tag 'index01.png'

.container
  .row     
    .span12.images-description
      .row
        .span7
          = image_tag 'index02.jpg' 
        .span5.margin-security
          %h3 Segurança
          %p 
            Seus dados 
            %strong protegidos 
            em 
            %strong robustos 
            servidores de 
            %strong alta performance. 
          %p 
            %strong Criptografia, backups automáticos, sigilo 
            e 
            %strong confidencialidade.
           
      

app/views/home/orders.html.haml
.banner
  .container
    = render "layouts/actionbar", user: current_user

.container.background-column.gold
  .row
    .span3
      = render "layouts/sidebar", user: current_user

    .span9
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Histórico de Pedidos

      %hr

      - if @orders.total_count > 0
        - @orders.each do |order|
          - if current_user.brand?
            = render "orders/order_view", order: order
          - elsif current_user.store?
            = render "orders/reverse_order_view", order: order
        = paginate @orders
      - else
        %p
          %i Você ainda não fez nenhum pedido. Quando os fizer, eles aparecerão aqui.
        %br
        .hr-arabesc

app/views/home/privacy.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar.about
      %ul.nav.nav-list.bs-docs-sidenav
        %li
          %a{:href => about_path}
            Empresa
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li.active
          %a{:href => privacy_path}
            Privacidade
            %i.icon-chevron-right
        %li
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify

      %h2.margin-bottom3 Privacidade

      %p A Privacidade da sua empresa é extremamente importante para o FashionHub, e mantemos rígidos padrões para mantê-la integra e segura.
      %p 
        Nossa Politica de Privacidade tem como objetivo,manter total transparência com relação às informações que recolhemos no site 
        %a{href: "http://www.fashionhub.com.br/"} www.fashionhub.com.br
        , e como essas informações são utilizadas.
      %p Ao se registrar no FashionHub, você está automaticamente de acordo e aceita as práticas descritas nesta Politica de Privacidade.
      
      %h2.margin-bottom3 Quais informações nós coletamos?
      
      %p As informações coletadas durante sua navegação no FashionHub, nos capacita a desenvolver e implementar melhorias nos nossos serviços. Coletamos os seguintes tipos de informações do Usuário: 
      %ol
        %li
          %p
            Informações cadastrais:
            Ao se cadastrar no FashionHub, solicitamos o preenchimento de um formulário, com dados tais como:
            Email, CNPJ, Endereço, Razão Social, Nome Fantasia, Telefone.
            Esses dados são necessários para ativação da conta do Usuário.
        %li 
          %p Endereço de IP e informações técnicas do seu computador ou dispositivo móvel, tais como: tipo de dispositivo, web browser ou sistema operacional.
        %li 
          %p Utilização das funcionalidades e histórico de atividades dentro da plataforma.
        %li 
          %p Quando um usuário entra em contato com o FashionHub, mantemos um registro das comunicações. 
            
      %h2.margin-bottom3 Como utilizamos as informações coletadas?
      
      %p O FashionHub utiliza as informações coletadas para fornecer os serviços solicitados.
      %p O FashionHub utiliza as informações coletadas para melhorar a experiência do usuário e a qualidade dos nossos serviços, identificar e resolver possíveis problemas técnicos.
      %p O FashionHub pode utilizar as informações coletadas para fornecer-lhe informações adicionais sobre os serviços, parceiros, promoções e eventos da empresa.  
      %p O conteúdo publicado em seu perfil pessoal, poderá ser acessado por outros usuários do FashionHub. 
      %p O FashionHub não comercializa, sob-hipotese alguma, nenhuma informação pessoal de seus usuários com terceiros.
      %p O FashionHub poderá fornecer dados do usuário a empresas provedoras de serviços da nossa plataforma. Por exemplo, nosso provedor de serviços de emails, através do qual são enviadas nossas newsletters e listas de email marketing. 
      %p Somos radicalmente contra spams.
      %p O FashionHub poderá fornecer dados do Usuário a terceiros, (a) caso seja determinado judicialmente, (b) por consentimento do próprio Usuário, (c)para proteger nossos direitos, reputação, propriedade, ou de nossos Usuários.
      %p Nenhum link de outros websites no conteúdo do FashionHub, se aplica esta Política de Privacidade, e não temos controle de tais sites de terceiros.
       
      %h2.margin-bottom3 Alterações e Atualizações
      
      %p Esta Politica de privacidade poderá sofrer alterações periódicas, portanto sugerimos consultá-la ocasionalmente para verificar possíveis atualizações. 
      %p 
        %b A última atualização foi realizada em: 12/03/2014.
        
      .hr-arabesc.margin-top2

app/views/home/register.html.haml
.banner
  .container
    .background-register
      Para fazer parte do FASHION
      %strong
        HUB
      %br
      %span
        precisamos primeiro saber quem você representa:
      %br
      .hr-arabesc.white
      .container-btn
        = link_to new_brand_path, :class => "btn btn-big btn-primary pull-left" do
          %i.icon-chevron-left.left
          Marca
        = link_to new_store_path, :class => "btn btn-big btn-primary pull-right" do
          Loja
          %i.icon-chevron-right
        .clearfix
    

        

app/views/home/store.html.haml
.container 
  .main-content.content-image-description
  
    .row
      .span12.title
        %h1.small-font-weight.text-center Sua Loja modernizando
        %h3.small-font-weight.text-center o processo de compra
        %br
        .hr-arabesc.margin-bottom2
      .row
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexbrand05.png' 
            .span5
              %h3 Acesse Coleções
              %p Acesse coleções antes de visitar o showroom ou feiras.
        
        .span12.images-description
          .row
            .span5.margin-security
              %h3 Descubra
              %p Descubra novas marcas.
            .span4.pull-right
              = link_to register_detail_path do
                = image_tag 'indexstore02.png'
  
        -#.span12.hr-arabesc
  
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexstore03.png' 
            .span5
              %h3 Planejamento
              %p Planejamento mais eficiente, melhores compras para a sua loja!
              
        .span12.images-description
          .row
            .span5
              %h3 Rentabilidade
              %p Reduza os custos com viagens / maior rentabilidade para seu negócio.
            .span4.pull-right
              = link_to register_detail_path do
                = image_tag 'indexstore04.png'
          
        .span12.images-description
          .row
            .span7
              = link_to register_detail_path do
                = image_tag 'indexstore05.png' 
            .span5
              %h3 Mais conveniência
              %p Mais conveniência ao realizar seus pedidos / em qualquer lugar e a qualquer momento.
        .span12.hr-arabesc.margin
        
        .row
          .span12.text-center
            = link_to new_store_path, :class => "btn btn-primary" do
              Fazer meu Cadastro como Loja
              %i.icon-chevron-right