config/routes.rb
Fashionhub::Application.routes.draw do
  mount RailsAdmin::Engine => '/fh-admin', as: 'rails_admin'

  devise_for :users
  resources :carts do
    resources :products do
      member do
        delete :remove
      end
    end
    resources :brands do
      member do
        post :order
      end
    end
  end
  resources :stores
  resources :brands do
    resources :brand_files
    resources :collections do
      resources :products
    end
    resources :orders
  end
  resources :favorites do
    member do
      post :product
      post :collection
      post :favorite
    end
  end
  resources :connections, only: [] do
    member do
      post :request_brand
      put :accept_store
      delete :refuse_store
      post :request_store
      put :accept_brand
      delete :refuse_brand
    end
  end
  resources :messages
  resources :search

  root to: 'home#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :dashboard do
      member do
        post 'user_approval'
      end
      collection do
        get 'orders'
        get 'transactions'
      end
    end
  end

  match "painel", to: "home#dashboard", via: 'get', as: 'dashboard_detail'
  match "loja", to: "home#store", via: 'get', as: 'store_detail'
  match "marca", to: "home#brand", via: 'get', as: 'brand_detail'
  match "favorito", to: "home#favorite", via: 'get', as: 'favorite_detail'
  match "activities", to: "home#activities", via: 'get', as: 'activities_detail'
  match "registro", to: "home#register", via: 'get', as: 'register_detail'
  match "conexao", to: "home#connection", via: 'get', as: 'connection_detail'

  match "empresa", to: "home#about", via: 'get', as: 'about'
  match "termos", to: "home#terms_use", via: 'get', as: 'terms'
  match "privacidade", to: "home#privacy", via: 'get', as: 'privacy'
  match "contato", to: "home#contact", via: 'get', as: 'contact'
  post 'contact', to: 'home#send_contact', as: 'send_contact'
  get 'historico-compras', to: 'home#orders', as: 'history_orders'


  # Tirar quando for implementar a página da Marca
  if Rails.env.development?
    match "email", to: "home#layout_email", via: 'get', as: 'email_detail'
  end
  #match "marca_fechada", :to => "home#brand_closed", :via => 'get', :as => 'brand_closed_detail'
  #match "produto", :to => "home#product", :via => 'get', :as => 'product_detail'
  #match "carrinho", :to => "home#cart", :via => 'get', :as => 'cart_detail'
  #match "colecao", :to => "home#collection", :via => 'get', :as => 'collection_detail'
  #match "upload_arquivo", :to => "home#upload_file", :via => 'get', :as => 'upload_file_detail'
  #match "nova_colecao", :to => "home#create_collection", :via => 'get', :as => 'create_collection_detail'
  #match "editar_colecao", :to => "home#edit_collection", :via => 'get', :as => 'edit_collection_detail'
  #match "novo_produto", :to => "home#create_product", :via => 'get', :as => 'create_product_detail'
  #match "editar_produto", :to => "home#edit_product", :via => 'get', :as => 'edit_product_detail'
  #match "editar", :to => "home#edit_profile", :via => 'get', :as => 'edit_detail'
  #match "editar_loja", :to => "home#edit_profile_store", :via => 'get', :as => 'edit_store_detail'
  #match "buscar", :to => "home#search", :via => 'get', :as => 'search'

  namespace :dev do
    resources :mailing do
      collection do
        get 'confirmation'
        get 'password'
        get 'user_approved'
        get 'user_refused'
        get 'contact'
      end
    end
  end
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :store

  has_many :items
  accepts_nested_attributes_for :items

  def total_items
    self.items.sum(:quantity)
  end

  def total_cost
    self.items.map{ |i| i.product.price * i.quantity }.reduce(&:+)
  end

  def brand_items
    self.items.group_by{ |i| i.product.collection.brand }
  end
  
  def remove_items_by_product prod_id
    self.items.where(product_id: prod_id).destroy_all
  end

  def items_by_brand brand_id
    items.joins(product: {collection: :brand}).where('users.id = ?', brand_id)
  end

  def update_items params
    transaction do |t|
      update(params)
      removals = params[:items_attributes].select{|i| i[:quantity] == '' }.map{|i| i[:id]}
      self.items.where('id in (?)', removals).destroy_all
      Favorite.where(product_id: self.items.map(&:product_id).uniq).destroy_all
    end
    true
  end

  def create_order brand_id, store_id
    transaction do |t|
      if Connection.where(brand_id: brand_id, store_id: store_id, accepted: true)
        _items = items_by_brand brand_id
        order = Order.create(brand_id: brand_id, store_id: store_id, pending: true)
        _items.update_all order_id: order.id, cart_id: nil
        #Favorite.where(product_id: _items.map(&:product_id).uniq).destroy_all
      end
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  respond_to :html
  before_action :set_cart
  before_filter :check_cart_owner, only: [:show, :update]

  def show
  end

  def update
    unless cart_params[:items_attributes].empty?
      flash[:notice] = "Carrinho atualizado!" if @cart.update_items(cart_params)
      if params[:command] == 'cart'
        respond_with @cart, location: cart_path(@cart)
      elsif params[:command] == 'brand'
        respond_with @cart, location: brand_path(params[:brand_id])
      elsif params[:command] == 'favorite'
        respond_with @cart, location: favorite_detail_path
      end
    else
      flash[:alert] = "Nenhum item selecionado."
      prod = Product.find params[:cart][:items_attributes].map{ |i| i['product_id'] }.first
      redirect_to brand_collection_product_path(prod.collection.brand, prod.collection, prod)
    end
  end

  private
    def cart_params
      sanitize_cart_params(params.require(:cart).permit(items_attributes: [:id, :quantity, :color_id, :size_id, :product_id]))
    end

    def sanitize_cart_params params
      params['items_attributes'] = params['items_attributes'].select { |y| not y['id'].blank? or not y['quantity'].blank? }
      params
    end

    def set_cart
      @cart = Cart.find(params[:id]) if params[:id]
    end
end

app/helpers/carts_helper.rb
module CartsHelper

  def total_items items
  	items.map{ |i| i.quantity }.sum()
  end

  def total_items_price items
  	number_to_currency items.map{ |i| i.quantity * i.product.price }.sum()
  end

  def items_releases items
  	map = {true => "Lançamento", false => "Pronta Entrega"}
  	items.map{ |i| map[i.product.collection.release] }.uniq.join ' e '
  end
end

app/views/carts/show.html.haml
.banner
  .container
    = render 'layouts/actionbar', user: current_user

.container
  .row
    .span12
      .collection-title
        %h2
          - if signed_in? and current_user.brand?
            = link_to current_user.name, brand_path(current_user)
          - elsif signed_in? and current_user.store?
            = link_to current_user.name, store_path(current_user)
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
        %h1
          %a Carrinho de Compras

      %hr

      .row
        .span12

          %h4.title.title-cart
            .pull-left
              %a.text
                Compras Pendentes
            .pull-right
              = link_to history_orders_path, class: "more button" do
                Histórico de Compras
                = image_tag 'ico-arrow-right.png'

          - unless @cart.total_items > 0
            %p
              %i Você não possui nenhum ítem no seu carrinho.
            %br
            .hr-arabesc
          - else
            .cart-list
              - counter = 0
              - @cart.brand_items.each do |brand, items|
                - counter += 1
                %table.table.cart-brand
                  %thead
                    %tr
                      %td.left-text{colspan: "6"}
                        %a
                          %h3= brand.name
                    %tr
                      %td.brand-profile{rowspan: "2"}
                        = image_tag brand.logo
                      %td
                        Total de Peças
                      %td
                        Entrega
                      %td
                        Valor Total
                      %td.btn-confirm{rowspan: "2"}
                        %a.btn.btn-disabled.btn-block{data:{toggle: "collapse"}, href: "#collapseDescription#{counter}"}
                          Editar
                      %td.btn-confirm{rowspan: "2"}
                        = link_to "Confirmar", order_cart_brand_path(@cart, brand), class: "btn btn-disabled btn-block", data:{method:'post'}
                      %td.arrow-down{rowspan: "2"}
                        %a{data:{toggle: "collapse"}, href: "#collapseDescription#{counter}"}
                          = image_tag 'ico-arrow-down.png'
                    %tr
                      %td= total_items items
                      %td= items_releases items
                      %td= total_items_price items

                .collapse{id:"collapseDescription#{counter}"}
                  %table.table.table-striped.cart-brand
                    - items.group_by{ |i| i.product }.each do |prod, prod_items|
                      %tr
                        %th &nbsp;
                        %th.left-text Nome do Produto
                        %th Quantidade
                        %th Preço Unitário
                        %th Total
                        %th &nbsp;
                      %tr
                        %td.img-product
                          = link_to image_tag(prod.representative_sample), brand_collection_product_path(prod.collection.brand, prod.collection, prod)
                        %td.left-text
                          = link_to prod.name, brand_collection_product_path(prod.collection.brand, prod.collection, prod)
                        %td= prod_items.map { |i| i.quantity }.sum()
                        %td= number_to_currency prod.price
                        %td= number_to_currency prod_items.map { |i| i.quantity }.sum()*prod.price
                        %td
                          = link_to image_tag('ico-edit.png'), brand_collection_product_path(prod.collection.brand, prod.collection, prod), data:{ toogle: :tooltip }, title: "Editar"
                          = link_to image_tag('ico-remove.png'), remove_cart_product_path(@cart, prod), data:{ method: :delete, toogle: :tooltip }, title: "Remover"

                    %tr
                      %td &nbsp;
                      %td &nbsp;
                      %td &nbsp;
                      %td &nbsp;
                      %td
                        %strong= total_items_price items
                      %td &nbsp;