config/routes.rb
Fashionhub::Application.routes.draw do
  mount RailsAdmin::Engine => '/fh-admin', as: 'rails_admin'

  devise_for :users
  resources :carts do
    resources :products do
      member do
        delete :remove
      end
    end
    resources :brands do
      member do
        post :order
      end
    end
  end
  resources :stores
  resources :brands do
    resources :brand_files
    resources :collections do
      resources :products
    end
    resources :orders
  end
  resources :favorites do
    member do
      post :product
      post :collection
      post :favorite
    end
  end
  resources :connections, only: [] do
    member do
      post :request_brand
      put :accept_store
      delete :refuse_store
      post :request_store
      put :accept_brand
      delete :refuse_brand
    end
  end
  resources :messages
  resources :search

  root to: 'home#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :dashboard do
      member do
        post 'user_approval'
      end
      collection do
        get 'orders'
        get 'transactions'
      end
    end
  end

  match "painel", to: "home#dashboard", via: 'get', as: 'dashboard_detail'
  match "loja", to: "home#store", via: 'get', as: 'store_detail'
  match "marca", to: "home#brand", via: 'get', as: 'brand_detail'
  match "favorito", to: "home#favorite", via: 'get', as: 'favorite_detail'
  match "activities", to: "home#activities", via: 'get', as: 'activities_detail'
  match "registro", to: "home#register", via: 'get', as: 'register_detail'
  match "conexao", to: "home#connection", via: 'get', as: 'connection_detail'

  match "empresa", to: "home#about", via: 'get', as: 'about'
  match "termos", to: "home#terms_use", via: 'get', as: 'terms'
  match "privacidade", to: "home#privacy", via: 'get', as: 'privacy'
  match "contato", to: "home#contact", via: 'get', as: 'contact'
  post 'contact', to: 'home#send_contact', as: 'send_contact'
  get 'historico-compras', to: 'home#orders', as: 'history_orders'


  # Tirar quando for implementar a página da Marca
  if Rails.env.development?
    match "email", to: "home#layout_email", via: 'get', as: 'email_detail'
  end
  #match "marca_fechada", :to => "home#brand_closed", :via => 'get', :as => 'brand_closed_detail'
  #match "produto", :to => "home#product", :via => 'get', :as => 'product_detail'
  #match "carrinho", :to => "home#cart", :via => 'get', :as => 'cart_detail'
  #match "colecao", :to => "home#collection", :via => 'get', :as => 'collection_detail'
  #match "upload_arquivo", :to => "home#upload_file", :via => 'get', :as => 'upload_file_detail'
  #match "nova_colecao", :to => "home#create_collection", :via => 'get', :as => 'create_collection_detail'
  #match "editar_colecao", :to => "home#edit_collection", :via => 'get', :as => 'edit_collection_detail'
  #match "novo_produto", :to => "home#create_product", :via => 'get', :as => 'create_product_detail'
  #match "editar_produto", :to => "home#edit_product", :via => 'get', :as => 'edit_product_detail'
  #match "editar", :to => "home#edit_profile", :via => 'get', :as => 'edit_detail'
  #match "editar_loja", :to => "home#edit_profile_store", :via => 'get', :as => 'edit_store_detail'
  #match "buscar", :to => "home#search", :via => 'get', :as => 'search'

  namespace :dev do
    resources :mailing do
      collection do
        get 'confirmation'
        get 'password'
        get 'user_approved'
        get 'user_refused'
        get 'contact'
      end
    end
  end
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, presence: true

  belongs_to :collection
  belongs_to :product_category

  has_and_belongs_to_many :colors
  accepts_nested_attributes_for :colors

  has_and_belongs_to_many :sizes
  accepts_nested_attributes_for :sizes

  has_many :product_samples, dependent: :destroy
  accepts_nested_attributes_for :product_samples, allow_destroy: true

  has_many :items
  has_many :favorites

  def representative_sample
    product_samples.first.sample unless product_samples.empty?
  end

  def favorited_by?(store)
    self.favorites.where(store_id: store.id).count > 0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :html
  before_action :set_product

  before_filter :check_current_user_authorization, only: [:edit, :update, :destroy, :new, :create]
  before_filter :check_current_user_store_connected_to_brand, only: [:index, :show]
  before_filter :check_cart_owner, only: [:remove]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @cart = current_user.shopping_cart if current_user.type == "Store"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.collection = @collection
    flash[:notice] = "Produto criado com sucesso!" if @product.save
    respond_with(@brand, @product, location: edit_brand_collection_path(@brand, @collection))
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    flash[:notice] = "Coleção atualizado com sucesso!" if @product.update(product_params)
    respond_with(@brand, @collection, location: edit_brand_collection_path(@brand, @collection))
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to edit_brand_collection_path(@brand, @collection) }
      format.json { head :no_content }
    end
  end

  # DELETE /carts/:cart_id/products/:id/remove
  def remove
    flash[:notice] = "Produto removido do carrinho"
    cart = Cart.find(params[:cart_id])
    cart.remove_items_by_product(params[:id])
    redirect_to cart_path cart
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id]) if params[:id]
      @collection = Collection.find(params[:collection_id]) if params[:collection_id]
      @brand = Brand.find(params[:brand_id]) if params[:brand_id]
    end

    def product_params
      params.require(:product).permit(:name, :code, :price, :description, :composition, :model, :product_category_id ,color_ids: [], size_ids: [], product_samples_attributes: [:id, :sample, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def product_image product
  	(product.representative_sample ? product.representative_sample : 'no-product.jpg')
  end

end

app/views/products/edit.html.haml
.banner
  .container
    =render "layouts/actionbar", user: @brand

.container.container-main
  .row          
    .span12
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
          = link_to "Gerenciamendo de Coleções", new_brand_collection_path(@brand)
          &#187;
          = link_to @collection.name, edit_brand_collection_path(@brand, @collection)
          &#187;
        %h1
          %a.ellipsis= @product.name
          
      %hr    
      
      .row
        .span12
          = simple_form_for([@brand, @collection, @product]) do |f|
            %fieldset
              
              %h4.title.margin-no
                .pull-left
                  %a.text
                    Fotos do Produto
              
              .row.controls-row
                = f.simple_fields_for :product_samples do |ps|
                  = render 'product_sample_fields', f: ps
                .span12
                  = link_to_add_association 'Adicionar Foto', f, :product_samples, class: "btn btn-disabled"            
                  
                  
            %fieldset
              %h4.title
                .pull-left
                  %a.text
                    Detalhes do Produto
              
              .row.controls-rowrir
                = f.input :name, wrapper_html: { class: 'span8' }, input_html: { class: 'span8' }
                = f.input :code, wrapper_html: { class: 'span2' }, input_html: { class: 'span2' }
                = f.input :price, wrapper_html: { class: 'span2' }, input_html: { class: 'span2' }
              
              .row.controls-row   
                = f.input :description, wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 2 }
                = f.input :composition, wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 2 }

              .row.controls-row 
                = f.input :model, placeholder: "Altura da Peça, Tamanho da Peça na Foto...", wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 3 } 
              
              .row.controls-row.product-category
                .span12
                  %label Categoria*
                  .border
                    .row
                      - ProductCategory.order(:name).each do |size|
                        %label.checkbox.span2
                          = f.radio_button :product_category_id, size.id
                          = size.name
                          
              .row.controls-row                               
                .span12
                  %label Tamanho*
                  .border
                    .row
                      - Size.order(:name).each do |size|
                        %label.checkbox.span2
                          %input{type: "checkbox", name: 'product[size_ids][]', value: size.id, checked: @product.sizes.map(&:id).include?(size.id)}= size.name

              .row.controls-row                               
                .span12
                  %label Cores*
                  .border
                    .row
                      - Color.order(:name).each do |color|
                        %label.checkbox.span2
                          %input{type: "checkbox", name: 'product[color_ids][]', value: color.id, checked: @product.colors.map(&:id).include?(color.id)}= color.name
  
            .hr-arabesc.margin
            
            %button.btn.btn-medium.btn-primary.pull-right
              Salvar
            
            = link_to "Excluir Produto", brand_collection_product_path(@brand, @collection, @product), data:{method: :delete},class: "btn btn-disabled pull-right margin-right"
              

app/views/products/new.html.haml
.banner
  .container
    =render "layouts/actionbar", user: @brand

.container.container-main
  .row
    .span12
      .collection-title
        %h2
          = render "layouts/userpage", user: current_user
          &#187;
          = link_to "Painel", dashboard_detail_path
          &#187;
          = link_to "Gerenciamendo de Coleções", new_brand_collection_path(@brand)
          &#187;
          = link_to @collection.name, brand_collection_path(@brand, @collection)
          &#187;
        %h1
          %a Novo Produto

      %hr

      .row
        .span12
          = simple_form_for([@brand, @collection, @product]) do |f|
            %fieldset

              %h4.title.margin-no
                .pull-left
                  %a.text
                    Fotos do Produto

              .row.controls-row
                = f.simple_fields_for :product_samples do |ps|
                  = render 'product_sample_fields', f: ps
                .span12
                  = link_to_add_association 'Adicionar Foto', f, :product_samples, :class => "btn btn-disabled"


            %fieldset
              %h4.title
                .pull-left
                  %a.text
                    Detalhes do Produto

              .row.controls-row
                = f.input :name, wrapper_html: { class: 'span8' }, input_html: { class: 'span8' }
                = f.input :code, wrapper_html: { class: 'span2' }, input_html: { class: 'span2' }
                = f.input :price, wrapper_html: { class: 'span2' }, input_html: { class: 'span2' }

              .row.controls-row
                = f.input :description, wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 2 }
                = f.input :composition, wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 2 }

              .row.controls-row
                = f.input :model, placeholder: "Altura da Peça, Tamanho da Peça na Foto...", wrapper_html: { class: 'span6' }, input_html: { class: 'span6', row: 3 }

              .row.controls-row.product-category
                .span12
                  %label Categoria*
                  .border
                    .row
                      - ProductCategory.order(:name).each do |size|
                        %label.checkbox.span2
                          = f.radio_button :product_category_id, size.id
                          = size.name

              .row.controls-row
                .span12
                  %label Tamanho*
                  .border
                    .row
                      - Size.order(:name).each do |size|
                        %label.checkbox.span2
                          %input{type: "checkbox", name: 'product[size_ids][]', value: size.id}= size.name

              .row.controls-row
                .span12
                  %label Cores*
                  .border
                    .row
                      - Color.order(:name).each do |color|
                        %label.checkbox.span2
                          %input{type: "checkbox", name: 'product[color_ids][]', value: color.id}= color.name

            .hr-arabesc.margin

            %button.btn.btn-medium.btn-primary.pull-right
              Cadastrar
              %i.icon-chevron-right

app/views/products/show.html.haml
.banner
  .container
    = render 'layouts/actionbar_brand'

.container
  .row
    .span12
      .collection-title
        %h2
          = link_to @brand.name, brand_path(@brand)
          &#187;
          = link_to @collection.name, brand_collection_path(@brand, @collection)
          &#187;
        %h1
          %a= @product.name

      %hr

      .row
        .span12
          .img-zoom
            %ul#etalage
              - @product.product_samples.each do |sample|
                %li= image_tag sample.sample, class: "etalage_source_image"

          .details.product-details
            .product-title
              .pull-left
                %p
                  %span= "Referência: " + (@product.code.blank? ? '' : "#{@product.code}")
                  = number_to_currency(@product.price)
              .pull-right
                -# TODO: mudar estilo do botão ao favoritar
                - if current_user.store?
                  = link_to product_favorite_path(@product), class: "btn btn-icon #{@product.favorited_by?(current_user) ? 'btn-primary': 'btn-disabled'}", data: {method: :post} do
                    Favorito
                    - unless @product.favorited_by? current_user
                      = image_tag 'ico-favorite.png'
                    - else
                      %i.icon-ok
              .clearfix
            %p
              %span
                %a
                  Descrição
                .product-description
                  - if @product.description.blank?
                    %i Produto sem descrição
                  - else
                    = @product.description
                    %a.readmore
                      Leia Mais &#187;

            %span
              %a.accordion-toggle{ data: { toggle: "collapse" }, href: "#collapseDescription"}
                Descrição Técnica &#187;
              #collapseDescription.collapse
                %table.table.table-details
                  %thead
                    %tr
                      %td Data Estimada da Entrega
                      %td= @collection.delivery_date
                    %tr
                      %td Composição
                      %td= @product.composition
                    %tr
                      %td Modelo
                      %td= @product.model
                    %tr
                      %td Tamanhos
                      %td
                        - @product.sizes.each do |size|
                          - name = size.name
                          - if name.size > 3
                            .box.size= name[0..1]
                          - else
                            .box.size= name[0..1]
                    %tr
                      %td Cores
                      %td
                        - @product.colors.each do |color|
                          .box{style: "background:#{color.code}"}

            %br
            - if current_user.store?
              = render "table_buy", product: @product, cart: @cart, favorite: false

        .span12
          %h4.title
            .pull-left
              %a.text
                Produtos Relacionados
            .pull-right
              %a.left.button{href: '#myCarouselProduct', data: {slide: 'prev'} }
              %a.right.button{href: '#myCarouselProduct', data: {slide: 'next'} }


          #myCarouselProduct.myCarousel.slide
            .carousel-inner
              = render 'layouts/product_carousel', product: @product

= render 'brands/payment_conditions'